language: android
jdk: oraclejdk8


cache:
  apt: true
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
    - ${TRAVIS_BUILD_DIR}/android-sdk/extras/

env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a

git:
  depth: 1

android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

script:
  - ./gradlew build assembleAndroidTest jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    on_success: always
    rooms:
      - werockstar:wl61Y86uYultyrQHTR3RE9Cx#ci_notifys
