language: android
jdk: oraclejdk8


cache:
  apt: true
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
    - ${TRAVIS_BUILD_DIR}/android-sdk/extras/

env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a

git:
  depth: 1

android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

script:
  - ./gradlew build assembleAndroidTest jacocoTestReport
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    on_success: always
    rooms:
      - werockstar:wl61Y86uYultyrQHTR3RE9Cx#ci_notifys
